routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\LogsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/** 后台 */
Route::name('admin.')->group(function () {
    /** 登录 */
    Route::get('admin/login', [LoginController::class, 'login'])->name('login');
    Route::post('admin/loginCheck', [LoginController::class, 'loginCheck'])->name('loginCheck');
    Route::get('admin/logout', [LoginController::class, 'logout'])->name('logout');

    /** 控制台 */
    Route::get('admin/home', [HomeController::class, 'home'])->name('home');
    /** 管理员 */
    Route::get('admin/user', [UserController::class, 'list'])->name('user');
    Route::get('admin/user/create', [UserController::class, 'create'])->name('user.create');
    Route::post('admin/user/store', [UserController::class, 'store'])->name('user.store');
    Route::get('admin/user/edit/{id}', [UserController::class, 'edit'])->name('user.edit');
    Route::post('admin/user/update', [UserController::class, 'update'])->name('user.update');
    Route::post('admin/user/delete/{id}', [UserController::class, 'delete'])->name('user.delete');
    /** 角色 */
    Route::get('admin/role', [RoleController::class, 'list'])->name('role');
    Route::get('admin/role/create', [RoleController::class, 'create'])->name('role.create');
    Route::post('admin/role/store', [RoleController::class, 'store'])->name('role.store');
    Route::get('admin/role/edit/{id}', [RoleController::class, 'edit'])->name('role.edit');
    Route::post('admin/role/update', [RoleController::class, 'update'])->name('role.update');
    Route::post('admin/role/delete/{id}', [RoleController::class, 'delete'])->name('role.delete');
    /** 日志 */
    Route::get('admin/logs', [LogsController::class, 'list'])->name('logs');
    Route::get('admin/logs/show/{id}', [LogsController::class, 'show'])->name('logs.show');

});

app/Http/Controllers/Admin/LoginController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\SysUser;
use App\Models\LogOperation;
use App\Enums\OperationCategory;
use App\Enums\OperationType;
use Illuminate\Support\Facades\Auth;

class LoginController extends Controller
{
    /**
     * 登录
     *
     */
    public function login() 
    {
        return view('admin.login.login');
    }
    
    /**
     *  登录校验
     *
     * @return void
     */
    public function loginCheck(Request $request) 
    {
        $request->validate([
            'username' => 'required|string',
            'password' => 'required|string',
            'captcha' => 'required|captcha',
        ]);
        
        /** @var SysUser $user */
        $user = SysUser::query()->where('username', $request->input('username'))->first();
        if (empty($user) || $user->disabled || !check_password($request->input('password'),$user->password)) {
            if (empty($user)) {
                $user = new SysUser();
                $user->fill([
                    'username' => $request->input('username')
                ]);
            }
            return redirect()->route('admin.login')->with(KEY_ALTER_ERROR, trans('auth.failed'));
        }
        $login_code=$user->createLoginCcode($user->username);
        $user->update(['login_time' => now(), 'login_ip' => $request->getClientIp(), 'login_code'=>$login_code]);
        
        Auth::login($user, $request->input('remember', false));
        LogOperation::log($user, OperationCategory::SystemUser(), OperationType::Login(), true, json_encode(['username'=>$user->username, 'status'=>'登录成功']));

        return redirect()->route('admin.home')
                         ->with(KEY_ALTER_SUCCESS, trans('alerts.system.title', ['message' => trans('app.login_success')]));
        
    }

    /**
     *  退出登录
     *
     * @return void
     */
    public function logout() 
    {
        Auth::logout();
        return redirect()->route('admin.login');
    }
}

resources/views/admin/login/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ __('app.login') }}</title>
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('/static/plugins/fontawesome-free/css/all.min.css') }}">
  <link rel="stylesheet" href="{{ asset('/static/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('/static/plugins/admin-lte/css/adminlte.min.css') }}">
  <link rel="stylesheet" href="{{ asset('/static/plugins/toastr/toastr.min.css') }}">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <!-- /.login-logo -->
  <div class="card card-outline card-primary">
    <div class="card-header text-center">
      <a href="javascript:;" class="h1">{{ __('app.login') }}</a>
    </div>
    <div class="card-body">
      <form action="{{ route('admin.loginCheck') }}" method="post">
        @csrf
        @if(session('error'))
          <div class="alert alert-danger">{{ session('error') }}</div>
         @endif
        <div class="input-group mb-3">          
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
          <input type="text"  class="form-control" name="username" placeholder="{{ __('app.helpers.username') }}" required value="admin">
          @error('username')
          <span class="error invalid-feedback d-block" role="alert"><strong>{{ $message }}</strong></span>
          @enderror
        </div>
        <div class="input-group mb-3">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
          <input type="password" class="form-control" name="password" placeholder="{{ __('app.helpers.password') }}" required value="admin">
          @error('password')
          <span class="error invalid-feedback d-block" role="alert"><strong>{{ $message }}</strong></span>
          @enderror
        </div>
        <div class="input-group mb-3">
          <input type="text" class="form-control" name="captcha" placeholder="{{ __('app.helpers.captcha') }}" required >
          <img src="{{captcha_src()}}" style="cursor: pointer" onclick="this.src='{{captcha_src()}}'+Math.random()">
          @error('captcha')
          <span class="error invalid-feedback d-block" role="alert"><strong>{{ $message }}</strong></span>
          @enderror
        </div>
        
        

        <div class="row">
          <button type="submit" class="btn btn-primary btn-block">{{ __('app.login') }}</button>
          <!-- /.col -->
        </div>
      </form>
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{{ asset('/static/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('/static/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('/static/plugins/admin-lte/js/adminlte.min.js') }}"></script>
<script src="{{ asset('/static/plugins/toastr/toastr.min.js') }}"></script>
@if(session('warning'))
    <script>toastr.warning('{{ session('warning') }}');</script>
@endif
</body>
</html>