routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\LogsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/** 后台 */
Route::name('admin.')->group(function () {
    /** 登录 */
    Route::get('admin/login', [LoginController::class, 'login'])->name('login');
    Route::post('admin/loginCheck', [LoginController::class, 'loginCheck'])->name('loginCheck');
    Route::get('admin/logout', [LoginController::class, 'logout'])->name('logout');

    /** 控制台 */
    Route::get('admin/home', [HomeController::class, 'home'])->name('home');
    /** 管理员 */
    Route::get('admin/user', [UserController::class, 'list'])->name('user');
    Route::get('admin/user/create', [UserController::class, 'create'])->name('user.create');
    Route::post('admin/user/store', [UserController::class, 'store'])->name('user.store');
    Route::get('admin/user/edit/{id}', [UserController::class, 'edit'])->name('user.edit');
    Route::post('admin/user/update', [UserController::class, 'update'])->name('user.update');
    Route::post('admin/user/delete/{id}', [UserController::class, 'delete'])->name('user.delete');
    /** 角色 */
    Route::get('admin/role', [RoleController::class, 'list'])->name('role');
    Route::get('admin/role/create', [RoleController::class, 'create'])->name('role.create');
    Route::post('admin/role/store', [RoleController::class, 'store'])->name('role.store');
    Route::get('admin/role/edit/{id}', [RoleController::class, 'edit'])->name('role.edit');
    Route::post('admin/role/update', [RoleController::class, 'update'])->name('role.update');
    Route::post('admin/role/delete/{id}', [RoleController::class, 'delete'])->name('role.delete');
    /** 日志 */
    Route::get('admin/logs', [LogsController::class, 'list'])->name('logs');
    Route::get('admin/logs/show/{id}', [LogsController::class, 'show'])->name('logs.show');

});

resources/views/admin/layouts/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>后台管理系统</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href=" {{ asset('/static/plugins/fontawesome-free/css/all.min.css') }} ">

  <!-- Ionicons -->
  <link rel="stylesheet" href=" {{ asset('https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css') }} ">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href=" {{ asset('/static/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }} ">
  <!-- iCheck -->
  <link rel="stylesheet" href=" {{ asset('/static/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }} ">
  <!-- Theme style -->
  <link rel="stylesheet" href=" {{ asset('/static/plugins/admin-lte/css/adminlte.min.css') }} ">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href=" {{ asset('/static/plugins/overlayScrollbars/css/OverlayScrollbars.min.css') }} ">
  <!-- Daterange picker -->
  <link rel="stylesheet" href=" {{ asset('/static/plugins/daterangepicker/daterangepicker.css') }} ">
  <link rel="stylesheet" href="{{ asset('/static/plugins/toastr/toastr.min.css') }}">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
  @yield('body')

<!-- ./wrapper -->

<!-- jQuery -->
<script src=" {{ asset('/static/plugins/jquery/jquery.min.js') }} "></script>
<!-- jQuery UI 1.11.4 -->
<script src=" {{ asset('/static/plugins/jquery-ui/jquery-ui.min.js') }} "></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src=" {{ asset('/static/plugins/bootstrap/js/bootstrap.bundle.min.js') }} "></script>
<!-- ChartJS -->
<script src=" {{ asset('/static/plugins/chart.js/Chart.min.js') }} "></script>
<!-- Sparkline -->
<script src=" {{ asset('/static/plugins/sparklines/sparkline.js') }} "></script>
<!-- daterangepicker -->
<script src=" {{ asset('/static/plugins/moment/moment.min.js') }} "></script>
<script src=" {{ asset('/static/plugins/daterangepicker/daterangepicker.js') }} "></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src=" {{ asset('/static/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }} "></script>
<!-- Summernote -->
<script src=" {{ asset('/static/plugins/summernote/summernote-bs4.min.js') }} "></script>
<!-- overlayScrollbars -->
<script src=" {{ asset('/static/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }} "></script>
<!-- bs-custom-file-input -->
<script src="{{ asset('/static/plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>

<script src="{{ asset('/static/plugins/sweetalert2/sweetalert2.all.min.js') }}"></script>
<script src="{{ asset('/static/plugins/toastr/toastr.min.js') }}"></script>
<!-- AdminLTE App -->
<script src=" {{ asset('/static/plugins/admin-lte//js/adminlte.js') }} "></script>
@stack('scripts')
</body>
</html>

resources/views/admin/layouts/main.blade.php
@extends('admin.layouts.base')

@section('body')
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link"  href="#" role="button">
           {{ Auth::user()->realname }}
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link btn btn-block btn-secondary"  href="{{ route('admin.logout') }}" style="color:#fff">
           退出          
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{ route('admin.home') }}" class="brand-link">
      <span class="brand-text font-weight-light">{{ __('app.system_name') }}</span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar Menu -->
      <x-nav-menu/>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  @yield('content')
  
  <!-- /.content-wrapper -->

</div>
@endsection

@push('scripts')
    @if(session('success'))
        <script>toastr.success('{{ session('success') }}');</script>
    @endif
    @if(session('info'))
        <script>toastr.info('{{ session('info') }}');</script>
    @endif
    @if(session('error'))
        <script>toastr.error('{{ session('error') }}');</script>
    @endif
    @if(session('warning'))
        <script>toastr.warning('{{ session('warning') }}');</script>
    @endif

    <script>
        $(function () {
            $('.x-logout').on('click', function (event) {
                event.preventDefault();
                $('#frm-logout').submit();
            });
        });
    </script>
@endpush