routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\LogsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/** 后台 */
Route::name('admin.')->group(function () {
    /** 登录 */
    Route::get('admin/login', [LoginController::class, 'login'])->name('login');
    Route::post('admin/loginCheck', [LoginController::class, 'loginCheck'])->name('loginCheck');
    Route::get('admin/logout', [LoginController::class, 'logout'])->name('logout');

    /** 控制台 */
    Route::get('admin/home', [HomeController::class, 'home'])->name('home');
    /** 管理员 */
    Route::get('admin/user', [UserController::class, 'list'])->name('user');
    Route::get('admin/user/create', [UserController::class, 'create'])->name('user.create');
    Route::post('admin/user/store', [UserController::class, 'store'])->name('user.store');
    Route::get('admin/user/edit/{id}', [UserController::class, 'edit'])->name('user.edit');
    Route::post('admin/user/update', [UserController::class, 'update'])->name('user.update');
    Route::post('admin/user/delete/{id}', [UserController::class, 'delete'])->name('user.delete');
    /** 角色 */
    Route::get('admin/role', [RoleController::class, 'list'])->name('role');
    Route::get('admin/role/create', [RoleController::class, 'create'])->name('role.create');
    Route::post('admin/role/store', [RoleController::class, 'store'])->name('role.store');
    Route::get('admin/role/edit/{id}', [RoleController::class, 'edit'])->name('role.edit');
    Route::post('admin/role/update', [RoleController::class, 'update'])->name('role.update');
    Route::post('admin/role/delete/{id}', [RoleController::class, 'delete'])->name('role.delete');
    /** 日志 */
    Route::get('admin/logs', [LogsController::class, 'list'])->name('logs');
    Route::get('admin/logs/show/{id}', [LogsController::class, 'show'])->name('logs.show');

});

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Admin\AdminController;
use Illuminate\Http\Request;
use App\Models\SysUser;
use App\Models\SysRole;
use App\Models\LogOperation;
use App\Enums\OperationCategory;
use App\Enums\OperationType;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use App\View\Components\NavMenu;


class RoleController extends AdminController
{
  
    public function list() 
    {
        /** @var SysUser $user */
        $roles=SysRole::query()->paginate(DEFAULT_PAGE_SIZE);
        return view('admin.role.list',['roles'=>$roles]);
    }

    public function create(NavMenu $navMenu) 
    {
        $menu=$navMenu->childrens();
        return view('admin.role.create',['menus'=>$menu]);
    }

    public function store(Request $request) 
    {
        Log::debug("Create a new role: ", $request->post());
        $request->validate([
            'name' => 'required|string|unique:sys_roles|max:32',
        ]);

        $role = new SysRole();
        $role->fill([
            'name' => \request('name'),
            'disabled' => \request('disabled'),
            'privileges' => implode(',', \request('privileges')),
        ]);
        $role->save();
        LogOperation::log(Auth::user(), OperationCategory::SystemRole(), OperationType::Create(), true, json_encode($role));
        return redirect()->route('admin.role')
                         ->with(KEY_ALTER_SUCCESS, trans('alerts.save.success', ['name' => trans('entities/role.name')]));

    }


    public function edit($id,NavMenu $navMenu) 
    {
        $menu=$navMenu->childrens();
        $roles=SysRole::query()->whereKey($id)->first();
        return view('admin.role.edit',['roles'=>$roles,'menus'=>$menu]);
    }

    public function update() 
    {
        $role = SysRole::query()->find(\request('id'));
        Log::debug("Update the role: ", $role->jsonSerialize());
        \request()->validate([
            'name' => 'required|string|max:32|unique:sys_roles,name,'.$role->id
        ]);
        $role->fill([
            'name' => \request('name'),
            'disabled' => \request('disabled'),
            'privileges' => implode(',', \request('privileges')),
        ]);
        $role->save();
        LogOperation::log(Auth::user(), OperationCategory::SystemRole(), OperationType::Update(), true, json_encode($role));
        return redirect()->route('admin.role.edit', $role->id)
                         ->with(KEY_ALTER_SUCCESS, trans('alerts.update.success', ['name' => trans('entities/role.name')]));
    }
    
    public function delete($id) 
    {
        $role = SysRole::query()->find($id);
        Log::debug("Delete the role: ", $role->jsonSerialize());
        $role->delete();
        LogOperation::log(Auth::user(), OperationCategory::SystemRole(), OperationType::Delete(), true, json_encode($role));
        return redirect()->route('admin.user')
                         ->with(KEY_ALTER_SUCCESS, trans('alerts.delete.success', ['name' => trans('entities/user.name')]));
    }
    
}

resources/views/admin/role/create.blade.php
@extends('admin.layouts.main')

@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ __('app.menus.sys_role') }}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">{{ __('app.home') }}</a></li>
              <li class="breadcrumb-item active">{{ __('app.menus.sys_role') }}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-6">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">{{ __('app.create') }}</h3>
            </div>
            <form action="{{ route('admin.role.store') }}" method="post">
              @csrf
            <div class="card-body">
              <div class="form-group">
                <label for="inputName">{{ __('entities/role.labels.name') }}</label>
                <input type="text" id="name" name="name" class="form-control" required>
                @error('name')
                <span class="error invalid-feedback d-block" role="alert"><strong>{{ $message }}</strong></span>
                @enderror
              </div>
              <div class="form-group">
                <label for="inputName">{{ __('entities/role.labels.privileges') }}</label>
                @foreach ($menus as $menu)
                <div class="custom-control custom-checkbox">
                  <input class="custom-control-input" type="checkbox" name="privileges[]" id="chk_{{ $menu['authCode'] }}" value="{{ $menu['authCode'] }}">
                  <label for="chk_{{ $menu['authCode'] }}" class="custom-control-label">{{ $menu['menu'] }}</label>
                </div>
                @endforeach         
              </div>
              <div class="form-group">
                <label for="inputName">{{ __('entities/user.labels.status') }}</label>
                <div class="custom-control custom-radio">
                  <input class="custom-control-input" type="radio" id="customRadio1" name="disabled" value="0" checked="">
                  <label for="customRadio1" class="custom-control-label">{{ __('entities/user.status.enabled') }}</label>
                </div>
                <div class="custom-control custom-radio">
                  <input class="custom-control-input" type="radio" id="customRadio2" name="disabled"  value="1">
                  <label for="customRadio2" class="custom-control-label">{{ __('entities/user.status.disabled') }}</label>
                </div>
                @error('disabled')
                <span class="error invalid-feedback d-block" role="alert"><strong>{{ $message }}</strong></span>
                @enderror
              </div>
            </div>    
            <!-- /.card-body -->
            <div class="card-footer">
              <button type="submit" class="btn btn-primary">{{ __('app.create') }}</button>
            </div>
          </form>
        </div>          
          <!-- /.card -->
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
@endsection

resources/views/admin/role/edit.blade.php
@extends('admin.layouts.main')

@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ __('app.menus.sys_role') }}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">{{ __('app.home') }}</a></li>
              <li class="breadcrumb-item active">{{ __('app.menus.sys_role') }}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-6">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">{{ __('app.edit') }}</h3>
            </div>
            <form action="{{ route('admin.role.update') }}" method="post">
              @csrf
            <input type="hidden" id="id" name="id" class="form-control" required  value="{{ $roles->id }}">
            <div class="card-body">
              <div class="form-group">
                <label for="inputName">{{ __('entities/role.labels.name') }}</label>
                <input type="text" id="name" name="name" class="form-control" required  value="{{ $roles->name }}">
                @error('name')
                <span class="error invalid-feedback d-block" role="alert"><strong>{{ $message }}</strong></span>
                @enderror
              </div>
              <div class="form-group">
                <label for="inputName">{{ __('entities/role.labels.privileges') }}</label>
                @foreach ($menus as $menu)
                <div class="custom-control custom-checkbox">
                  <input class="custom-control-input" type="checkbox" name="privileges[]" id="chk_{{ $menu['authCode'] }}" value="{{ $menu['authCode'] }}" @if($roles->hasPrivilege($menu['authCode'])) checked @endif>
                  <label for="chk_{{ $menu['authCode'] }}" class="custom-control-label">{{ $menu['menu'] }}</label>
                </div>
                @endforeach         
              </div>
              <div class="form-group">
                <label for="inputName">{{ __('entities/role.labels.status') }}</label>
                <div class="custom-control custom-radio">
                  <input class="custom-control-input" type="radio" id="customRadio1" name="disabled" value="0"  @if($roles->disabled === false) checked="" @endif >
                  <label for="customRadio1" class="custom-control-label">{{ __('entities/role.status.enabled') }}</label>
                </div>
                <div class="custom-control custom-radio">
                  <input class="custom-control-input" type="radio" id="customRadio2" name="disabled"  value="1" @if($roles->disabled === true) checked="" @endif >
                  <label for="customRadio2" class="custom-control-label">{{ __('entities/role.status.disabled') }}</label>
                </div>
                @error('disabled')
                <span class="error invalid-feedback d-block" role="alert"><strong>{{ $message }}</strong></span>
                @enderror
              </div>
            </div>    
            <!-- /.card-body -->
            <div class="card-footer">
              <button type="submit" class="btn btn-primary">{{ __('app.edit') }}</button>
            </div>
          </form>
        </div>          
          <!-- /.card -->
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
@endsection

resources/views/admin/role/list.blade.php
@extends('admin.layouts.main')

@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ __('app.menus.sys_role') }}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">{{ __('app.home') }}</a></li>
              <li class="breadcrumb-item active">{{ __('app.menus.sys_role') }}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-6" style="flex: 100%;max-width: 100%;">
            <div class="card">
              <!-- /.card-header -->
              <div class="card-header">
                <h3 class="card-title">
                 <a href="{{ route('admin.role.create') }}" class="btn btn-block btn-primary">{{ __('app.create') }}</a>
                </h3>
              </div>
              <div class="card-body">
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th style="width: 10px">ID</th>
                      <th>{{ __('entities/role.table.name') }}</th>
                      <th>{{ __('entities/role.table.status') }}</th>
                      <th>{{ __('app.operation') }}</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach ($roles as $role)
                    <tr>
                      <td>{{ $role->id }}</td>
                      <td>{{ $role->name }}</td>
                      <td>
                        @if($role->disabled)
                            <span class="badge bg-gray">{{ __('entities/role.status.disabled') }}</span>
                        @else
                            <span class="badge bg-green">{{ __('entities/role.status.enabled') }}</span>
                        @endif
                      </td>
                      <td>
                        <a class="btn btn-primary btn-sm" href="{{ route('admin.role.edit', $role->id) }}" title="{{ __('app.edit') }}">
                            <i class="fas fa-pencil-alt"></i>                          
                        </a>
                        @if ($role->id != 1)
                        <form action="{{ route('admin.role.delete', $role->id) }}" method="POST" style="display: inline;">
                          @csrf
                          <a class="btn btn-danger btn-sm x-delete" href="#" title="{{ __('app.delete') }}" data-id="{{ $role->id }}"><i class="fas fa-trash"></i></a>
                        </form>         
                        @endif
                    </td>
                    </tr>  
                    @endforeach             
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
              <div class="card-footer clearfix">
                {{ $roles->links() }}
              </div>
            </div>
          </div>
        </div> 
      </div>
    </section>
  </div>
  @endsection

  @push('scripts')
    <script type="application/javascript">
        $(function () {
            $('.x-delete').on('click', function (event) {
                console.info('Click the button to delete a Advert Picture.');
                event.preventDefault();
                const $form = $(this).parent('form');

                Swal.fire({
                    title: '{{ __('confirm.delete', ['name'=>'']) }}',
                    text: '{{ __('confirm.delete.description') }}',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonText: '{{ __('confirm') }}',
                    cancelButtonText: '{{ __('cancel') }}'
                }).then(function(result) {
                    if(result.value) {
                        $form.submit();
                    }
                });
            });
        })
    </script>
  @endpush